routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();
Auth::routes(['register'=>false]);

Route::get('/', 'HomeController@index')->name('home');

Route::resources([
    'link' => 'LinkController',
    'section' => 'SectionController'
 ]);

app/Link.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Link extends Model
{
	protected $fillable = [
        'link',
        'descripcion', 
        'section_id'
    ];

    public function section ()
    {
    	 return $this->belongsTo(Section::class);
    }

}

app/Section.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Section extends Model
{
	protected $fillable = [
        'nombre',
    ];

	public function links ()
   	{
    	return $this->hasMany(Link::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Section;
use App\Link;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //$this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $sections = Section::all();
        $links = Link::all();

        return view('home')->with([
            'sections' => $sections,
            'links' => $links
        ]);
    }
}

app/Http/Controllers/LinkController.php
<?php

namespace App\Http\Controllers;

use App\Link;
use Illuminate\Http\Request;

class LinkController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request->all());
        if (Link::create($request->all())) {
            return back()->with('success','Nuevo link '.$request->nombre.' guardado!!');
        }else{
            return back()->with('error','Error al guardar link '.$request->nombre.'!!');
        }
       // Link::create($request->all());
        //dd($request->all());
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Link  $link
     * @return \Illuminate\Http\Response
     */
    public function show(Link $link)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Link  $link
     * @return \Illuminate\Http\Response
     */
    public function edit(Link $link)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Link  $link
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Link $link)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Link  $link
     * @return \Illuminate\Http\Response
     */
    public function destroy(Link $link)
    {
        if ($link->delete()) {
            return back()->with('success','Link '.$link->link.' eliminado!!');
        }else{
            return back()->with('error','Error al eliminar link '.$link->link.'!!');
        }
    }
}

app/Http/Controllers/SectionController.php
<?php

namespace App\Http\Controllers;

use App\Section;
use Illuminate\Http\Request;

class SectionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (Section::create($request->all())) {
            return back()->with('success','Nueva seccion '.$request->nombre.' guardada!!');
        }else{
            return back()->with('error','Error al guardar seccion '.$request->nombre.'!!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Section  $section
     * @return \Illuminate\Http\Response
     */
    public function show(Section $section)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Section  $section
     * @return \Illuminate\Http\Response
     */
    public function edit(Section $section)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Section  $section
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Section $section)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Section  $section
     * @return \Illuminate\Http\Response
     */
    public function destroy(Section $section)
    {
        if ($section->delete()) {
            return back()->with('success','Link '.$section->nombre.' eliminado!!');
        }else{
            return back()->with('error','Error al eliminar link '.$link->link.'!!');
        }
    }
}

resources/views/home.blade.php
@extends ('layout.main')

@section('content')
<main class="main-container" role="main" >
	<img src="{{ asset('img/logo.png') }}" height="54" width="317" class="logo">
	@guest
	@else
	    <div id="">
        	<a class="btn btn btn-outline-dark m-2" style="background-color:transparent;" data-toggle="modal" data-target="#nuevoLink" data-item-id="TEST">Nuevo Link</a>
        	<a class="btn btn btn-outline-dark m-2" style="background-color:transparent;" data-toggle="modal" data-target="#nuevaSeccion" data-item-id="TEST">Nueva Sección</a>
        	<a class="btn btn btn-outline-dark m-2" style="background-color:transparent;" data-toggle="modal" data-target="#removeLink" data-item-id="TEST">Eliminar Link</a>
        	<a class="btn btn btn-outline-dark m-2" style="background-color:transparent;" data-toggle="modal" data-target="#removeSection" data-item-id="TEST">Eliminar Sección</a>
        </div> 
	@endguest
	@if ($message = Session::get('success'))
	<div class="alert alert-success alert-block">
	  <button type="button" class="close" data-dismiss="alert">×</button>
	  <strong>{{ $message }}</strong>
	</div>
	@endif

	@if ($message = Session::get('error'))
	<div class="alert alert-warning alert-block">
	  <button type="button" class="close" data-dismiss="alert">×</button>
	  <strong>{{ $message }}</strong>
	</div>
	@endif

	@if ($errors->any())
	<div class="alert alert-danger">
	  <ul>
	    @foreach ($errors->all() as $error)
	    <li>{{ $error }}</li>
	    @endforeach
	  </ul>
	</div><br />
	@endif

	<section>
		<div class="container">
			<div class="row">
				@foreach ($sections as $section)	
				<div id="accordion">
					<div class="card m-4">
						<div class="card-header" id="heading{{$section->id}}">
							<h5 class="mb-0">
								<button class="btn btn-link" data-toggle="collapse" data-target="#collapse{{$section->id}}" aria-expanded="true" aria-controls="collapse{{$section->id}}">
									<h2>{{$section->nombre}}</h2>
								</button>
							</h5>
						</div>
						<div id="collapse{{$section->id}}" class="collapse" aria-labelledby="heading{{$section->id}}" data-parent="#accordion">
							<div class="card-body">
								<ul>
									@foreach ($section->links()->get() as $link)
									<li><a href="{{$link->link}}" target="_blank">{{$link->link}} - {{$link->descripcion}}</a></li>
									@endforeach
								</ul>
							</div>
						</div>
					</div>
				</div>
				@endforeach
			</div>
		</div>
	</section>
</main>

@endsection
@include('modal')

resources/views/layout/head.blade.php
<head> 
    <title>{{ config('app.name', 'Laravel') }}</title>
	
	<meta charset="utf-8"/>
	<meta name="description" content="Recursos">
	<meta name="keywords" content="nofollow">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script type="text/javascript" src="{{asset('js/bootstrap.min.js')}}"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">

    <!-- Styles -->
	<link rel="shortcut icon" href="{{ asset('img/favicon.ico') }}" type="image/x-icon" />
	{{--<link rel="stylesheet" type="text/css" href="{{ asset('css/bootstrap.min.css') }}">--}}
   {{-- <link href="{{ asset('css/app.css') }}" rel="stylesheet">--}}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link type="text/css" rel="stylesheet" href="{{ asset('css/style.css') }}" />
	
</head>

resources/views/layout/header.blade.php
 <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto pull-right">
                <!-- Authentication Links -->
                @guest
                <li class="nav-item mr-4">
                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                </li>
                @if (Route::has('register'))
                {{--<li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                    </li>--}}
                @endif
                @else
                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link dropdown-toggle mr-4" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        {{ Auth::user()->name }} <span class="caret"></span>
                    </a>
               
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ route('logout') }}"
                        onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();">
                        {{ __('Logout') }}
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            </li>
            @endguest
        </ul>
    </div>
</div>
</nav>

resources/views/layout/main.blade.php
<!DOCTYPE html>
<html lang="es">
	@include ('layout.head')
	@yield('head')
	<body class="reloco">
		@include('layout.header')
		@yield ('content')
	</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/modal.blade.php
{{--MODAL NUEVO LINK--}}
<div class="modal" tabindex="-1" role="dialog" id="nuevoLink">
    <form action="{{ route('link.store') }}" method="POST" enctype="multipart/form-data">   
        @csrf
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="alert alert-danger" style="display:none"></div>
                <div class="modal-header">
                    <h5 class="modal-title">Nuevo Link</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="form-group col-md-12">
                            <label for="link">Link:</label>
                            <input type="text" class="form-control" name="link" id="link">
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-12">
                            <label for="descripcion">Descripción:</label>
                            <input type="text" class="form-control" name="descripcion" id="descripcion">
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-12">
                            <label for="seccion">Sección:</label>
                            <select class="form-control m-bot15" name="section_id">
                              @foreach ($sections as $section)
                                  <option value="{{$section->id}}">{{$section->nombre}}</option>
                              @endforeach
                            </select>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <button  class="btn btn-success" id="editSubmit">Guardar</button>
                </div>
            </div>
        </div>
    </form>
</div>

{{--MODAL ELIMINAR LINK--}}
<div class="modal" tabindex="-1" role="dialog" id="removeLink">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="alert alert-danger" style="display:none"></div>
            <div class="modal-header">
                <h5 class="modal-title">Eliminar Link</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="panel-body">
                    <ul class="list-group">
                        @foreach ($links as $link)
                        <form action="{{ route('link.destroy',$link->id) }}" method="POST" enctype="multipart/form-data">   
                            @csrf
                            {{ method_field('DELETE') }}
                            <li class="list-group-item">
                                {{$link->link}} - {{$link->descripcion}}
                                 <button  class="btn btn-success">Eliminar</button>
                            </li>
                        </form>
                    @endforeach
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        </div>
    </div>
</div>


{{--MODAL NUEVA SECCION--}}
<div class="modal" tabindex="-1" role="dialog" id="nuevaSeccion">
    <form action="{{ route('section.store') }}" method="POST" enctype="multipart/form-data">   
        @csrf
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="alert alert-danger" style="display:none"></div>
                <div class="modal-header">
                    <h5 class="modal-title">Nueva Sección</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="form-group col-md-12">
                            <label for="Name">Nombre:</label>
                            <input type="text" class="form-control" name="nombre" id="nombre">
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <button  class="btn btn-success" id="editSubmit">Guardar</button>
                </div>
            </div>
        </div>
    </form>
</div>

{{--MODAL ELIMINAR SECCION--}}
<div class="modal" tabindex="-1" role="dialog" id="removeSection">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="alert alert-danger" style="display:none"></div>
            <div class="modal-header">
                <h5 class="modal-title">Eliminar Seccion</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="panel-body">
                    <ul class="list-group">
                        @foreach ($sections as $section)
                        <form action="{{ route('section.destroy',$section->id) }}" method="POST" enctype="multipart/form-data">   
                            @csrf
                            {{ method_field('DELETE') }}
                            <li class="list-group-item">
                                {{$section->nombre}}
                                 <button  class="btn btn-success">Eliminar</button>
                            </li>
                        </form>
                    @endforeach
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        </div>
    </div>
</div>